version: "3.7"
services:
        app:
                container_name: php
                image: php:8.1.0alpha3-fpm-alpine 
                ports:
                        - "9000:9000"
                volumes:
                        - ./nginx/html:/var/www/html
        web:
                container_name: nginx
                build:
                        context: ./nginx
                        dockerfile: dockerfile
                depends_on:
                        - app
                volumes:
                        - ./nginx/html:/var/www/html
                        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
                ports:
                        - "8888:8888"
                        - "443:443"
                links:
                        - app
                restart: always
